version: '3.8'

services:
  app:
    image: tarunkumar573/contacts-app:latest
    container_name: contacts-app
    ports:
      - "8501:8501"
    environment:
      # These should match what your app expects
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=mydatabase
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
